# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UI12_TableView综合' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UI12_TableView综合

pod 'SDWebImage'

  target 'UI12_TableView综合Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
